using Flunt.Notifications;
using System;

namespace PaymentContext.Shared.Entities
{
    public abstract class Entity : Notifiable<Notification>
    {
        /*
         * The idea behind the 'Entity' class is to differentiate entities (models) from VOs (value objects).
         * 
         * ValueObjects don't have an 'Id' property and they are complex types created to add value and functionality to otherwise simple - but 
         * recurrent tasks such as having a "string Email" field that would need to be validated across the application.
         */
        public Entity()
        {
            /*
             * Using a 'Guid' to be an Id - instead of an 'int' - has its Pros and Cons.
             * 
             * According to the instructor of the course (Balta), using a Guid that is generated by the application means that we would have "one less hit"
             * on the database, despite losing on performance on searches through indexed values...
             * 
             * I'm not really sure if this is worthy.
             */
            Id = Guid.NewGuid();
        }

        public Guid Id { get; private set; }
    }
}
